### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pop' in installing fabric dependencies

### ISSUE THREAD

**Issue by nimaafraz** [hyperledger-labs/umbra#25]
```
nimaafraz@umbra-1:~/umbra/examples$ python3 fabric/local-2orgs.py
Traceback (most recent call last):
  File "fabric/local-2orgs.py", line 202, in <module>
    builds()
  File "fabric/local-2orgs.py", line 166, in builds
    experiment.save()
  File "/home/nimaafraz/umbra/umbra/design/basis.py", line 847, in save
    data = self.dump()
  File "/home/nimaafraz/umbra/umbra/design/basis.py", line 837, in dump
    topo_built = self.topology.build()
  File "/home/nimaafraz/umbra/umbra/design/fabric.py", line 721, in build
    self.build_configs()
  File "/home/nimaafraz/umbra/umbra/design/fabric.py", line 790, in build_configs
    self._build_config_sdk()
  File "/home/nimaafraz/umbra/umbra/design/fabric.py", line 1140, in _build_config_sdk
    "path": orderer_tls_file.pop(),
AttributeError: 'NoneType' object has no attribute 'pop'

```

I'm guessing this has something to do with the error in installing fabric dependencies:

```
mkdir: cannot 
create directory ‘git’: File exists
fatal: could not create work tree dir 'git/fabric-sdk-py': Permission denied
./deps_fabric.sh: line 52: cd: git/fabric-sdk-py: No such file or directory
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by nimaafraz** [comment]
Issue resolved after a restart and: `sudo apt update` , `sudo apt upgrade`
Closing this
